name: Build V8

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-v8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: build
      run: |
        sh ./v8-linux.sh

        rm -rf ./v8/v8/out.gn/x64.release/obj
        rm -rf ./v8/v8/out.gn/x64.release/gen
        cd ./v8/v8/out.gn
        tar -czf v8-x86_64-unknown-linux-gnu.tar.gz ./x64.release
        # cd v8
        # mkdir -p out/release
        # tools/dev/v8gen.py x64.release
        # ninja -C out/release
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: v8-x86_64-unknown-linux-gnu
        path: ./v8/v8/out.gn/v8-x86_64-unknown-linux-gnu.tar.gz
