name: Build V8

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-v8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    # - name: Setup Build Environment
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y python3 python3-pip git build-essential ninja-build clang cmake pkg-config curl

    # - name: Clone V8
    #   run: |
    #     git clone https://chromium.googlesource.com/v8/v8.git
    #     cd v8
    #     git checkout stable
    #     gclient sync

    - name: Build V8
      run: |
        sh ./v8-linux.sh

        # cd v8
        # mkdir -p out/release
        # tools/dev/v8gen.py x64.release
        # ninja -C out/release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: v8-build
        path: ~/v8/v8/out.gn/x64.release
