name: build

permissions:
  contents: write

on:
  push:
    branches:
      - "main"
    tags:
      - v*
  schedule:
    - cron: "0 0 * * 1"
  pull_request:

jobs:
  build-x86_64-unknown-linux-gnu:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: build
        run: |
          sh ./v8-linux.sh

      - name: tar
        run: |
          rm -rf ~/v8/v8/out.gn/x64.release/obj
          rm -rf ~/v8/v8/out.gn/x64.release/gen
          cd ~/v8/v8/out.gn
          tar -czf v8-x86_64-unknown-linux-gnu.tar.gz -C x64.release .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: v8-x86_64-unknown-linux-gnu
          path: ~/v8/v8/out.gn/v8-x86_64-unknown-linux-gnu.tar.gz
      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: ~/v8/v8/out.gn/v8-x86_64-unknown-linux-gnu.tar.gz

  build-x86_64-apple-darwin:
    if: false
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: build
        run: |
          sh ./v8-macos.sh

          rm -rf ./v8/v8/out.gn/x64.release/obj
          rm -rf ./v8/v8/out.gn/x64.release/gen
          cd ./v8/v8/out.gn
          tar -czf v8-x86_64-apple-darwin.tar.gz -C x64.release .
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: v8-x86_64-apple-darwin
          path: ./v8/v8/out.gn/v8-x86_64-apple-darwin.tar.gz

  build-x86_64-pc-windows-msvc:
    if: false
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: build
        shell: cmd
        run: |
          call .\v8-windows.cmd

          rmdir .\v8\v8\out.gn\x64.release\obj
          rmdir .\v8\v8\out.gn\x64.release\gen

          cd .\v8\v8\out.gn
          tar -czf v8-x86_64-pc-windows-msvc.tar.gz -C x64.release .
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: v8-x86_64-pc-windows-msvc
          path: ./v8/v8/out.gn/v8-x86_64-pc-windows-msvc.tar.gz

  # build:
  #   needs: [
  #       "build-x86_64-unknown-linux-gnu",
  #       # "build-windows",
  #       # "build-macos-x86_64",
  #       # "build-macos-aarch64",
  #     ]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Download All Artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         path: v8
  #         pattern: v8-*
  #         merge-multiple: true

  #     - name: release
  #       if: startsWith(github.ref, 'refs/tags/')
  #       uses: ncipollo/release-action@v1
  #       with:
  #         artifacts: "v8/*.tar.gz"
